### ISSUE TITLE
Add screen-specific screenshots to sim checklist

### ISSUE THREAD

**Issue by arouinfar** [phetsims/phet-info#189]
See https://github.com/phetsims/website/issues/1322

In addition to alternate screenshots that show up on the sim page, we should also be taking screen-specific screenshots for the metadata service. Alt and screen-specific screenshots may be redundant but aren't necessarily.

Self-assigning to update the sim checklist.

**Comment by arouinfar** [comment]
Sim checklists to update:

- [ ] geometric-optics
- [ ] geometric-optics-basics
- [ ] greenhouse-effect
- [ ] buoyancy
- [ ] my-solar-system
- [ ] number-play
- [ ] center-and-spread
- [ ] eating-exercise-and-energy
- [ ] calculus-grapher
- [ ] build-a-nucleus
- [ ] normal-modes
- [ ] x-ray-diffraction

**Comment by arouinfar** [comment]
Done, except for calculus-grapher which I noted in https://github.com/phetsims/calculus-grapher/issues/1.

**Comment by arouinfar** [comment]
The instructions I added to the sim checklist were too vague. Screen-specific screenshots should be taken with the `screens` query parameter. Re-opening to update the checklist template and checklists for sims in active development.

- [ ] template checklist
- [ ] greenhouse-effect
- [ ] buoyancy
- [ ] my-solar-system
- [ ] number-play
- [ ] number-compare
- [ ] center-and-variability
- [ ] eating-exercise-and-energy
- [ ] build-a-nucleus
- [ ] normal-modes
- [ ] models-of-the-hydrogen-atom
- [ ] x-ray diffraction
- [ ] calculus-grapher
