### ISSUE TITLE
"Code review" appears twice in sim-checklist.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#220]
In https://github.com/phetsims/phet-info/commit/3b23e8d91f4747e68ff5bf16159f801dfedc6169, @samreid add this item to sim-checklist.md:

> - [ ] **Code review checklist completed"** (Date: //)

In addition to the typo, there are now 2 "code review" items in the checklist:

<img width="455" alt="screenshot_2961" src="https://github.com/phetsims/phet-info/assets/3046552/f77ecc91-ff7b-4240-be7d-d1da6404e1eb">

**Comment by samreid** [comment]
Thanks, I fixed the typo and removed an extraneous "code review" item. I'm not very clear on the order of "QA first look" "QA dev test" and "Code review".  The checklist currently says:

```
- [ ] **Development started** (Date: //)
- [ ] **Sim is "feature complete"** (Date: //)
- [ ] **QA team "first look"** (Date: //)
- [ ] Interviews may happen around here (see above)
- [ ] **Sim team sign-off** (Date: //)
- [ ] **Code review completed** (Date: //)
- [ ] **Sim dev test completed** (Date: //)
- [ ] **Sim RC tests completed** (Date: //)
```

https://github.com/phetsims/circuit-construction-kit-common/issues/692#issue-865549463 says dev test should be before code review. That was back in April 2021 and I'm not sure whether that is still accurate. Also, that comment doesn't mention the "QA Team First Look" so I'm not sure if that is the thing that is supposed to happen before code review.

On Projectile Data Lab, we have the code review scheduled before the dev test. I'm not sure if that is accurate: https://github.com/orgs/phetsims/projects/85/views/1

@marlitas or @pixelzoom can you please double check and comment?

**Comment by marlitas** [comment]
I would imagine that we want code review to be before a dev test. It is likely that there are large code changes that happen from a code review that would require QA to run a dev test again either way... 

I'm not convinced by the comments in https://github.com/phetsims/circuit-construction-kit-common/issues/692#issue-865549463 . Generally developers and designers have interacted with the sim thoroughly before a code review so any large bugs that would require another code review would have been discovered by that point. This is also running under the assumption that developers are reviewing their own code the entire time, including when addressing QA bugs. I have generally seen the main impact of the large "Code Review" as an overview of the entire architecture to suss out brittle or problematic implementations. These types of things should definitely be addressed prior to the QA process. 

I haven't seen a "first look" happen on a project yet, but that could have been before me. I don't see the harm in it, but I would expect that a "first look" may be dependent on the QA workload as well. Would this type of QA test use the "dev-lite" template?

**Comment by pixelzoom** [comment]
The revised checklist looks OK to me.

Code review happens before dev test.  When a dev testing is completed, the goal is to create the release branch ASAP, and begin RC testing, so there is no time for code review.   And a code review can result in major changes to the code -- something to be avoided once a sim is in the QA pipeline.

**Comment by pixelzoom** [comment]
Back to @samreid, feel free to close.

**Comment by samreid** [comment]
Excellent, thanks @marlitas and @pixelzoom. Closing.
