### ISSUE TITLE
check for PhetColorScheme in code-review checklist?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#90]
PhetColorScheme has gotten out of date (https://github.com/phetsims/scenery-phet/issues/456), and sims aren't using it when they should be. E.g.:

ESP: phetsims/energy-skate-park#51
MAS: phetsims/masses-and-springs#343
Pendulum Lab: phetsims/pendulum-lab#209
Hooke's Law: https://github.com/phetsims/hookes-law/issues/70

Shall we add this item to the code-review checklist? 

- [ ] Verify that the sim is using `PhetColorScheme` where appropriate, and is not inventing/creating its own colors for things that are (or should be) standardized. 

@arouinfar FYI.  @ariel-phet assigned to you in case you want to make a decision on this before developer meeting discussion.

**Comment by ariel-phet** [comment]
@pixelzoom seems appropriate, please add.

**Comment by pixelzoom** [comment]
On closer inspection, I added these 3 items to the check list:

- [ ] Are there any [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)) that should be factored out as constants and documented?
- [ ] Are there any constants that are duplicated in multiple files that should be factored out into a `{{REPO}}Constants.js` file?
- [ ] Is [PhetColorScheme](https://github.com/phetsims/scenery-phet/blob/master/js/PhetColorScheme.js) used where appropriate? Verify that the sim is not inventing/creating its own colors for things that have been standardized in `PhetColorScheme`.  Identify any colors that might be worth adding to `PhetColorScheme`.

Closing.
